
<label for='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' class=\'required\'' ?>><?= $this->get_title() ?></label>
<? if (!$this->get_inline()): ?><br /><? endif ?>
<textarea name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' data-required=\'true\'' ?>><?= $this->get_prefilled_value() ?></textarea>
<script>
  tinyMCE.init({
    selector: '#<?= $this->get_name() ?>',
    language: 'de',
    menubar: false,
    toolbar_sticky: true,
    plugins: 'fullscreen table charmap lists wordcount tinymcespellchecker',
    toolbar: 'undo redo | formatselect | bold italic underline | fontsize | alignleft aligncenter alignright alignjustify | numlist bullist | outdent indent | fullscreen removeformat'
    });
</script>