<div class='<?= $this->get_class_list() ?>'>
    <? if ($this->is_collapsible()): ?>
        <table class="header">
            <tr>
                <td>
                    <label for='<?= $this->get_name() ?>' <? if ($this->is_required())
                    echo ' class=\'required\'' ?>>
                    <?= $this->get_title() ?>
                </label>
            </td>
            <td class="right">
                <span class="collapse-editor" data-editor="<?= $this->get_name() ?>"><i class="fa fa-chevron-down"></i></span>
            </td>
        </tr>
    </table>
    <? else: ?>
        <label for='<?= $this->get_name() ?>' <? if ($this->is_required())
        echo ' class=\'required\'' ?>>
        <?= $this->get_title() ?>
    </label>
    <? endif ?>
    <hr>
    <div class="body" data-editor="<?= $this->get_name() ?>">
        <textarea name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>' <? if ($this->is_required())
            echo ' data-required=\'true\'' ?>><?= $this->get_prefilled_value() ?></textarea>
    <script>
        tinyMCE.init({
            selector: '#<?= $this->get_name() ?>',
            language: 'de',
            menubar: false,
            toolbar_sticky: true,
            contextmenu: false,
            browser_spellcheck: true,
            plugins: '<?= $this->get_plugin_list() ?>',
            toolbar: [<?= $this->get_toolbar_list() ?>],
            paste_as_text: true
        });
        </script>
    </div>
</div>